services:
  postgres:
    image: postgres:16-alpine
    container_name: desing_elite_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: desing_elite_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@desing_elite.online
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: desing_elite_api
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
